package org.example.rpcProtocol.request;

public enum RequestType {
    LOGIN, LOGOUT, SIGNUP, GET_TRIPS, BUY_TICKET, GET_TRIP, GET_TRIP_ID, GET_BOOKED_SEATS, GET_CUSTOMER_NAME, GET_CHECK_IF_SEAT_RESERVED, GET_ALL_RESERVATIONS
}
